/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 21-Jun.-2019 18:35:54 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

use DBDiags
go

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Account_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Account] DROP CONSTRAINT [FK_Account_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Bitacora_Account]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Bitacora] DROP CONSTRAINT [FK_Bitacora_Account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Token_PasswordAccount]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Token] DROP CONSTRAINT [FK_Token_PasswordAccount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Token_Account]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Token] DROP CONSTRAINT [FK_Token_Account]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Account]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Bitacora]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Bitacora]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Passwordaccount]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Passwordaccount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Token]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Token]
GO

/* Create Tables */

CREATE TABLE [Account]
(
	[Email] nvarchar(320) NULL,
	[Fechacreacion] datetime NULL,
	[Telefono] char(9) NULL,
	[NombreUsuario] nvarchar(125) NOT NULL,
	[ClienteID] int identity(1,1) NOT NULL
)
GO

CREATE TABLE [Bitacora]
(
	[Ingreso] datetime NULL,
	[Salida] datetime NULL,
	[BitacoraID] int NOT NULL,
	[AccountID] nvarchar(125) NULL
)
GO

CREATE TABLE [Cliente]
(
	[ApellidosCliente] nvarchar(40) NULL,
	[FechaNacimiento] datetime NULL,
	[NombreCliente] nvarchar(45) NULL,
	[Sexo] char(10) NULL,
	[Dni] char(8) Primary Key NOT NULL
)
GO

CREATE TABLE [PasswordAccount]
(
	[PasswordString] nvarchar(350),
	[HashCode] nvarchar(350),
	[PasswordAccountID] int Primary Key Not Null
)
GO

CREATE TABLE [Hashtable]
(
	[HashCode] nvarchar(350) Primary Key Not Null,
)
GO

CREATE TABLE [AccountHashTable]
(
	[HashCode] nvarchar(350),
	[NombreUsuario] nvarchar(125),
	[Activa] bit,
	[AccountHashID] int identity(1,1) Primary Key Not Null
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Account] 
 ADD CONSTRAINT [PK_Account]
	PRIMARY KEY CLUSTERED ([NombreUsuario] ASC)
GO

ALTER TABLE [Bitacora] 
 ADD CONSTRAINT [PK_Bitacora]
	PRIMARY KEY CLUSTERED ([BitacoraID] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([ClienteID] ASC)
GO


/* Create Foreign Key Constraints */

ALTER TABLE [Account] ADD CONSTRAINT [FK_Account_Cliente]
	FOREIGN KEY ([Dni]) REFERENCES [Cliente] ([Dni]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Bitacora] ADD CONSTRAINT [FK_Bitacora_Account]
	FOREIGN KEY ([AccountID]) REFERENCES [Account] ([NombreUsuario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PasswordAccount] ADD CONSTRAINT [FK_HashTable]
	FOREIGN KEY ([HashtableID]) REFERENCES [Hashtable] ([HashtableID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AccountHashTable] ADD CONSTRAINT [FK_AccountHashTable_Hash]
	FOREIGN KEY ([HashtableID]) REFERENCES [Hashtable] ([HashtableID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AccountHashTable] ADD CONSTRAINT [FK_AccountHashTable_Account]
	FOREIGN KEY ([NombreUsuario]) REFERENCES [Account] ([NombreUsuario]) ON DELETE No Action ON UPDATE No Action
GO