/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 26-Jun.-2019 12:22:57 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HashTable]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Passwordaccount] DROP CONSTRAINT [FK_HashTable]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Hashtable]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Hashtable]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Passwordaccount]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Passwordaccount]
GO

/* Create Tables */

CREATE TABLE [Hashtable]
(
	[Hash] nvarchar(350) NULL,
	[HashtableID] int NOT NULL
)
GO

CREATE TABLE [Passwordaccount]
(
	[Passwordstring] nvarchar(350) NULL,
	[HashTableID] int NULL,
	[PasswordaccountID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Hashtable] 
 ADD CONSTRAINT [PK_Hashtable]
	PRIMARY KEY CLUSTERED ([HashtableID] ASC)
GO

ALTER TABLE [Passwordaccount] 
 ADD CONSTRAINT [PK_Passwordaccount]
	PRIMARY KEY CLUSTERED ([PasswordaccountID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Passwordaccount] ADD CONSTRAINT [FK_HashTable]
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO
